### ISSUE TITLE
Bug in compressor ?

### ISSUE THREAD

**Issue by christophermh44** [CSCSI/Triana#3]
In https://github.com/CSCSI/Triana/blob/master/triana-toolboxes/audio/src/main/java/audio/processing/dynamic/CompressorEffect.java

In the method called gainSideChain(), currentCorrection is always set to 0.
Then this comparison is done:

    if (correction < currentCorrection) { … } else { … }

So, the "if" will never be called, and the "else" always. Is this normal?

(BTW, I'm trying to adapt this script in JS and then I will try to add sidechain filter on the compressor)

---

UPDATE 2:

My bad. I misunderstood this if!
But still have the impression my JS translation does not work :(

---

UPDATE 3:

After reading again, here is what I understand:

- When the correction is computed, it always will be 0 if excursion <= 0 (reference in dB < threshold)
- So, when the currentCorrection is computed, if reference in dB < threshold we'll always release the signal, because correction will be = 0. Is this really that we need?

(sorry for spam, I'm trying to understand :) )

---

UPDATE 4:

Here is my implementation of your compressor: http://utopic-radio.c-mh.fr/sandbox/

**Comment by christopher-mh** [comment]
My bad. I misunderstood this if!
But still have the impression my JS translation does not work :(

**Comment by christophermh44** [comment]
Can be closed. Resolved by using some other algorithms.
